### ISSUE TITLE
Upgrade to latest version of 'modify-babel-preset'

### ISSUE THREAD

**Issue by HenningM** [bkonkle/babel-preset-es2015-loose#11]
[This pull request](https://github.com/developit/modify-babel-preset/pull/3) includes a fix for a bug with module resolution in 'modify-babel-preset'. It was merged before the release of version 2.0.2.

**Comment by uhtred** [comment]
How do you solve for now? @HenningM

**Comment by bkonkle** [comment]
Thanks for letting me know! I'll ugrade now!

**Comment by bkonkle** [comment]
@HenningM @uhtred - I don't have a project using `babel-preset-es2015-loose` at the moment so I don't have an easy way to test a real-world scenario. Can you try out the release candidate I pushed to npm and let me know if it works?

`npm install babel-preset-es2015-loose@next`

**Comment by uhtred** [comment]
Create a sample: https://github.com/uhtred/webpack-test

ps.: I use loose@next on tests, doesn't solve.

**Comment by jimthedev** [comment]
https://github.com/developit/modify-babel-preset/issues/12

I think this needs to be merged and released first.

**Comment by jimthedev** [comment]
@bkonkle I know you've deprecated this project but would you be willing to merge the latest version of modify-babel-preset and release a new version? It has a major fix relating to babel resolution that will allow this issue to be closed. Also, can we talk about transferring this project and npm privileges  to an organization so that it can live on?

**Comment by bkonkle** [comment]
Hi! I'll take a look at the branch again tonight and cut a new release. I didn't think there would still be a reason to keep actively developing this, but I'm realizing there are still teams on earlier versions of Babel that will keep using this indefinitely. I'm glad to continue maintaining it, and I'll add clarified notes about this project only being deprecated for projects using newer Babel versions.

**Comment by jimthedev** [comment]
@bkonkle great! Looking forward to it!

**Comment by bkonkle** [comment]
Okay, this has now been published, and we're on v3.1.0 of `modify-babel-preset`. 👍 Thanks!
